import "@/app/globals.css"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Aside from "@/components/Aside";
import NavMobile from "@/components/NavMobile";
import Header from "@/components/Header";
import HeaderMobile from "@/components/HeaderMobile";
import { AuthProvider } from "@/contexts/AuthContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PDE - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <div className="grid grid-cols-1 md:grid-cols-[220px_1fr] min-h-screen">
        <Aside />
        <NavMobile />

        <div>
          <HeaderMobile />

          <Header />
          <main className="pb-20 lg:pb-0">{children}</main>
        </div>
      </div>
    </AuthProvider>
  );
}