import "@/app/globals.css"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Aside from "@/components/Aside";
import NavMobile from "@/components/NavMobile";
import Header from "@/components/Header";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PDE - Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid grid-cols-1 md:grid-cols-[220px_1fr] min-h-screen">

    {/* Todo o conteúdo compartilhado fixo entre as telas da dashboard devem ficar aqui*/}
    <Aside perfil="orientador" />
    <NavMobile perfil="aluno" />

    <div>
      <Header nome="Dr. Ricardo Silva" perfil="orientador"/>
      <main>{children}</main>
    </div>
    </div>
  );
}
